export const skillsArr = [
  { id: 1, skillName: "HTML", value: 95 },
  { id: 2, skillName: "CSS", value: 80 },
  { id: 3, skillName: "JavaScript", value: 80 },
  { id: 4, skillName: "Tailwind CSS", value: 85 },
  { id: 5, skillName: "React JS", value: 85 },
  { id: 6, skillName: "MongoDB", value: 90 },
  { id: 7, skillName: "Express.js", value: 80 },
  { id: 8, skillName: "Node.js", value: 80 },
  { id: 9, skillName: "Git", value: 95 },
  { id: 10, skillName: "GitHub", value: 85 },
  { id: 11, skillName: "APIs", value: 95 },
  { id: 12, skillName: "Node.js", value: 85 },
  { id: 13, skillName: "Next.js", value: 80 },
  { id: 14, skillName: "Developer Tools", value: 90 },
  { id: 15, skillName: "Artificial Intelligence", value: 75 },
  { id: 16, skillName: "GitHub Copilot", value: 80 },
];
